export enum Role {
  PATIENT = 'PATIENT',
  JUNIOR_PHYSIO = 'JUNIOR_PHYSIO',
  CENTRAL_PHYSIO = 'CENTRAL_PHYSIO',
  NURSE = 'NURSE',
  SUPPORT = 'SUPPORT',
  ACCOUNTANT = 'ACCOUNTANT',
  CHARITY = 'CHARITY',
  DOCTOR = 'DOCTOR',
  ADMIN = 'ADMIN',
}
